# See https://docs.github.com/en/actions/guides for documentation about GitHub
# Actions.

name: AUnit Tests

# Run on all branches.
on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: |
        cd ..
    - name: Verify tests
      run: |
        make -C tests
